### ISSUE TITLE
Lodash should be a dependency, not a dev dependency

### ISSUE THREAD

**Issue by qgustavor** [kwonoj/electron-hunspell#32]
[`/dist/src/spellCheckerProvider.js`](https://unpkg.com/electron-hunspell@0.0.4/dist/src/spellCheckerProvider.js) requires Lodash, but [it's listed as a dev dependency](https://github.com/kwonoj/electron-hunspell/blob/aeba5f070188acd9760c4067b5d4ecc8a641fb1d/package.json#L68), which prevents [the package from working](https://wzrd.in/standalone/electron-hunspell).

**Comment by kwonoj** [comment]
oooooh yes you're right, thanks for catching it. Let me roll our fix shortly.

**Comment by kwonoj** [comment]
@qgustavor rolled out 0.0.5 https://github.com/kwonoj/electron-hunspell/releases/tag/v0.0.5 to include lodash correctly as dependency.

I'm still doubt linked wzrd.in may correctly working with this package (this package is intended for electron), but at least dependency issue should be resolved.

**Comment by qgustavor** [comment]
I'm planning to use Webpack to bundle the code Electron will be running (so
I can use ES modules) but in fact I just linked it to show the missing
package error.

2017/11/13 19:34 "OJ Kwon" <notifications@github.com>:
