### ISSUE TITLE
Find misspelled words

### ISSUE THREAD

**Issue by thiagorova** [kwonoj/electron-hunspell#326]
Hi! First of all, thanks a lot, this package is simply fantastic.
As you probably know, there isn't any way to see in the DOM a list of marked misspelled words. Do you think it's viable to add a findMisspelled method to the API. It could be very simple. It receives a string (or, If you'd like, a string array as well) and returns an array with all the words that the spellchecker would mark.

I'm not too familiar with typescript, but if you're ok with it I'd be willing to try to implement this!

**Comment by kwonoj** [comment]
That's what underlyng package https://github.com/kwonoj/hunspell-asm exposes - is there specific usecase you can't use interface of hunspell-asm?

**Comment by thiagorova** [comment]
well... to be quite honest I tried looking for it, but didn't find it. 
The test, from what I just discovered, is called spell and it's inside spellCheckerTable[dictionaryName].spellChecker. If you don't mind me asking here, I noticed that hunspell-asm also has the following methods that apparently aren't being exposed:

> `addWord(word: string):` void : add single word to current dictionary.
> `removeWord(word: string):` void : remove single word from current dictionary.
> `addWordWithAffix(word: string, affix: string):` void: add word with example word having affix flag to be applied. Second param affix is example word, should exists in current dictionary with its own affix flag. Newly added word will have same affix rule as example word.

Am I write that they are not being exposed, or did I also just not find them?
Thanks a lot and sorry for the dumb question...

**Comment by kwonoj** [comment]
It is true addword* is not exposed yet and that'll be in further update, not a high priority.

I believe you need to start to looking into hunspell-asm, as that is low level lib to control spellchecker features while this one supposed to wire electron's webframe. Hunspell-asm have both for check spell / get suggested words.

**Comment by thiagorova** [comment]
well... to be quite honest I really like how simple it is to integrate your package with electron. I'm managing the "add-remove" words for now by creating a new .dic file by combining the global dictionary downloaded by Hunspell-dict-downloader with my local word list (I mentioned this in another issue topic here). Using the `spell` method you exposed is also working fine for me, so that's not a problem either.

after seeing the method in Hunspell-asm, though, I was just wondering if you planned on exposing those methods as well. Since what I'm doing's working fine, I'm not in a hurry either.
thanks a lot!

**Comment by kwonoj** [comment]
Those 2 are different. `add*` is indeed needed in electron-hunspell and it'll be implemented. On the other hand, `getsuggestion` is internal in perspective of electron-hunspell as it needs to be passed to webframe, not intended to be used by other places. If someone needs spellchecking other than attaching into webframe like displaying it into dom or else, that's where you need to use hunspell-asm directly.

**Comment by sachinrekhi** [comment]
Really eager to see addWord() added to electron-hunspell! Last thing missing in making this the definitive Electron spell checker. Can't believe the performance improvement over electron-spellchecker!
