### ISSUE TITLE
Impossible to run with twitter?

### ISSUE THREAD

**Issue by guilhermewaess** [kwonoj/electron-hunspell#410]
Hello,

I'm using electron-hunspell and I'd like to say: great job!

Im wondering if there is a way to make it work when I have a webview with Twitter loaded inside, every time that I try to open twitter, I've faced this error which I think that is something particular from twitter

```
Uncaught (in promise) CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder
```

Any ideas?

**Comment by kwonoj** [comment]
That's due to host page (twitter)'s CSP policy does not allow compiling wasm binary not from trusted origin (twitter itself) for secutiry reasons.

Since twitter doesn't allow it, not sure if you can bypass it. Creating blob worker in preload before CSP setup in document then do async spellchecker might be way.

**Comment by chrisknepper** [comment]
@guilhermewaess @kwonoj 

I know this is months later, but I just saw this comment and wanted to say that yes, it is possible to use `electron-hunspell` within an Electron Webview whose host page sends a CSP policy header. I do this in my Electron app.

Electron provides an event listener on the Webview's webContents, `session.webRequest.onHeadersReceived` which allows you as the Electron developer to modify any headers sent by the page in the webview. The webview will then behave as if the page sent those headers originally. I use this method to allow `electron-hunspell` to work in my application's webview.

You can see how this works in my app: https://github.com/chrisknepper/android-messages-desktop/blob/e4514428d2478a539ecd81f4c8d73e91619f48d1/src/app.js#L35

Lines 35-72. You have to specify which URL(s) should be watched for their headers and you have to be careful about replacing the headers in a particular order.
