### ISSUE TITLE
SpellCheckerProvider.initialize() timeout parameter

### ISSUE THREAD

**Issue by sachinrekhi** [kwonoj/electron-hunspell#541]
I'm trying to provide timeout as an optional parameter in SpellCheckerProvider.initialize() as I occasionally hit the default timeout and get an error. However, I can't seem to figure out what the default timeout value is or what unit the timeout is in? I assume the timeout is specified in milliseconds, but wanted to be sure.

Would be great to add to the docs as well.

**Comment by kwonoj** [comment]
it's 3sec by default and ms. https://github.com/kwonoj/emscripten-wasm-loader/blob/master/src/constructModule.ts#L41-L47
