### ISSUE TITLE
Spell checker does not work with Electron 7.1.1

### ISSUE THREAD

**Issue by zikosichi** [kwonoj/electron-hunspell#550]
Uncaught (in promise) CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder

![image](https://user-images.githubusercontent.com/16005795/68593395-a601de80-0495-11ea-9ab7-39d41eb41270.png)

**Comment by kwonoj** [comment]
This is not electron error, mostly csp. Which page you are trying to load and what's csp configuration for thise pafe?

**Comment by zikosichi** [comment]
Yes, you are right. Just saw a similar issue on https://github.com/kwonoj/electron-hunspell/issues/410

**Comment by kwonoj** [comment]
Either you put provider into different worker or change remote site behavior, provider need to run under env supports wasm compilation.
