### ISSUE TITLE
SpellCheckerProvider.initialize() indirectly registers an unhandledRejection and an uncaughtException listener that terminate the process

### ISSUE THREAD

**Issue by stewartlord** [kwonoj/electron-hunspell#584]
If you load `electron-hunspell` into node and initialize `SpellCheckerProvider`, the underlying Emscripten build of `hunspell-asm` will have the side-effect of:
```
process["on"]("unhandledRejection", abort);
```
and
```
process['on']('uncaughtException', function(ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });
```
These are not desirable and are quite difficult/awkward to disable.

Recommend using a build with `NODEJS_CATCH_REJECTION = 0` and `NODEJS_CATCH_REJECTION = 0`

**Comment by kwonoj** [comment]
Yes, that sounds correct (while probably this issue can go directly to `hunspell-asm` 😅 ) Let me see if I can bring fixes.
