### ISSUE TITLE
Feature Request - Allow adding words to ignore spellcheck

### ISSUE THREAD

**Issue by mengfoobar** [kwonoj/electron-hunspell#66]
Great job on the lib! Works really with electron.

Just wondering if there is a way to add words to ignore in the spellchecker? I.e. the word *JSON* will always trigger spellcheck to mark it as incorrect. It would be extremely helpful if there is a way to add it to ignore list. 

Thanks

**Comment by kwonoj** [comment]
There isn't way currently. I have planned for upstream changes https://github.com/kwonoj/hunspell-asm/issues/96 but I can't promise exact date / version at this moment.

**Comment by kwonoj** [comment]
Closing for now while I track this via upstream issue.

**Comment by thiagorova** [comment]
I'm not gonna say this is the best possible way to do this, but you can technically add words straight to the .dic file. I mean, you need the path to the file to load it anyway. Until a better solution shows up, that is what I plan on doing, at least. (with the downside of having to reload the .dic when adding new words...)

The two biggest issue here are dealing with the .dic file affixes (I'm studying that right now, but it's quite a pain) and having with multiple minor document related dictionaries that you do not want to mix.
